# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssf?characterEncoding=utf8
    username: kkw
    password: ktf1686
    driver-class-name: com.mysql.cj.jdbc.Driver



#mybatis.type-aliases-package:flab.SSF.Community

mybatis:
  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
